name: Deploy to Cloud Run Function

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # 使用現有的 WIF 設定
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    # 部署到 Cloud Run Function
    - name: Deploy to Cloud Run Function
      run: |
        gcloud functions deploy hello_http_cicd \
          --gen2 \
          --runtime=python311 \
          --region=asia-east1 \
          --source=. \
          --entry-point=main \
          --trigger-http \
          --allow-unauthenticated \
          --quiet

