name: Deploy to Cloud Run Function

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: asia-east1
  SERVICE: app-engine-service
  REGION: asia-east1
  REPOSITORY: myapp  # 簡化的 repository 名稱

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker to use gcloud as credential helper
      run: |
        gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev
    
    # 確保 Artifact Registry repository 存在
    - name: Create Artifact Registry repository
      run: |
        gcloud artifacts repositories create $REPOSITORY \
          --repository-format=docker \
          --location=$GAR_LOCATION \
          --description="Docker repository" || echo "Repository already exists"
    
    # 簡化的 image 名稱
    - name: Build and Push Container
      run: |
        IMAGE_NAME="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:latest"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE \
          --image=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:latest \
          --region=$REGION \
          --allow-unauthenticated \
          --port=8080 \
          --memory=512Mi \
          --cpu=1 \
          --quiet
    
    - name: Show service URL
      run: |
        gcloud run services describe $SERVICE --region=$REGION --format='value(status.url)'
